name: Daily build

on:
  schedule:
    - cron: '0 12 * * *'

jobs:
  master:
    uses: 96boards/oe-rpb-manifest/.github/workflows/build-template.yml@qcom/master
    with:
      branch: master
    secrets: inherit

  qcom-master:
    uses: 96boards/oe-rpb-manifest/.github/workflows/build-template.yml@qcom/master
    with:
      branch: qcom/master
    secrets: inherit

  qcom-scarthgap:
    uses: 96boards/oe-rpb-manifest/.github/workflows/build-template.yml@qcom/master
    with:
      branch: qcom/scarthgap
    secrets: inherit

  qcom-kirkstone:
    uses: 96boards/oe-rpb-manifest/.github/workflows/build-template.yml@qcom/master
    with:
      branch: qcom/kirkstone
    secrets: inherit

  qcom-dunfell:
    uses: 96boards/oe-rpb-manifest/.github/workflows/build-template.yml@qcom/master
    with:
      branch: qcom/dunfell
    secrets: inherit
