name: Daily build

on:
  schedule:
    - cron: '0 12 * * *'

jobs:
  master:
    uses: ./.github/workflows/build-template.yml
    with:
      branch: qcom/master
    secrets: inherit

  kirkstone:
    uses: ./.github/workflows/build-template.yml
    with:
      branch: qcom/kirkstone
    secrets: inherit

  dunfell:
    uses: ./.github/workflows/build-template.yml
    with:
      branch: qcom/dunfell
    secrets: inherit
