name: PR build

on:
  pull_request_target:

jobs:
  build:
    uses: ./.github/workflows/build-template.yml
    with:
      branch: refs/pull/${{github.event.pull_request.number}}/head
      local_repo: ${{github.repository}}
      local_ref: refs/pull/${{github.event.pull_request.number}}/head
    secrets: inherit
